### ISSUE TITLE
BaseAuditLog must be interface

### ISSUE THREAD

**Issue by DangerLifter** [xiidea/EasyAuditBundle#19]
BaseAuditLog must be interface and be as less strict and verbose as possible. Only minimum set of methods for work support of common code should be defined,

**Comment by ronisaha** [comment]
As of version V1.4.4 we can use BaseAuditLog class directly, as it is no more an abstract class. This class contains all minimum sets i thought a AuditLogger should have. 
Could you please explain, which attributes you think is not needed for your use case.
And could you please explain what would be the benefits we will get by using interface instead of a class. 

Thanks
