### ISSUE TITLE
Incompatibility for 1.4.6 ->1.4.9

### ISSUE THREAD

**Issue by pausf** [xiidea/EasyAuditBundle#39]
Hi Ronin,

Versions 1.4.* should be compatible with each other and from 1.4.6 to 1.4.9 many errors occur. For example the function **"getBestCandidatePropertyForIdentify"** is no longer in the class **EntityEventResolver.**

Version 1.4.* **should** only be for improvements or bug fixes not such big code changes.

Thank you very much for the development

**Comment by ronisaha** [comment]
Sorry for the inconvenience, As i have treated the Default Entity Resolver as example implementation, I did made that changes ignoring the backward compatibility(My Bad). If you like the old implementation, please instead of extending, you can copy the content from [https://github.com/xiidea/EasyAuditBundle/blob/1.4.6/Resolver/EntityEventResolver.php](https://github.com/xiidea/EasyAuditBundle/blob/1.4.6/Resolver/EntityEventResolver.php)

For future reference I'll add an BC breaking note in the readme.

From now on I'll try harder to keep the backward compatibility.

Thank for your feedback.

**Comment by pausf** [comment]
Many thanks and good job
